# Generated by Django 5.0.6 on 2024-05-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residence_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apartment',
        ),
    ]
