# Generated by Django 5.0.6 on 2024-05-20 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_management', '0004_rename_studentdata_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residence_management.room'),
        ),
    ]
