# Generated by Django 5.0.6 on 2024-05-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_management', '0005_alter_student_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
