# Generated by Django 5.0.6 on 2024-05-24 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_management', '0008_remove_building_sex_of_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='residence_management.building'),
        ),
        migrations.AlterField(
            model_name='room',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='residence_management.apartment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='residence_management.room'),
        ),
    ]
