# Generated by Django 5.0.6 on 2024-05-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residence_management', '0009_remove_instructor_username_remove_student_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_photos/'),
        ),
    ]
